---
title: "Red spruce reflush in 2020"
author: "Anoob Prakash"
date: "16/03/2021"
output:
  rmarkdown::html_document:
    theme: cosmo  
    number_sections: false
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
require(ggalluvial)
require(ggsci)
require(tidyverse)
require(data.table)
require(lubridate)
require(plyr)
require(viridis)
require(lmerTest)
})

exome_meta <- read.table("C:\\Dropbox\\UVM\\Research\\Exome\\RS_Exome_metadata.txt", header = T, sep="\t")
```

# Data  {.tabset .tabset-fade .tabset-pills}  
## Vermont    
```{r}
## garden map
VT_gar <- read_csv("C:/Dropbox/Spruce_CommonGarden_Data/VT_site/VT_garden.csv")

## plant ID frame 
VT_frame <- VT_gar[,c("PlantOrder", "plant_ID")]


## VT files
VT_files <- list.files(path = "C:/Dropbox/Spruce_CommonGarden_Data/VT_site/VT_traitdataRAW/budset_2020", full.names = TRUE)

## Convert timestamp to date
VT_comb_files <- bind_rows(lapply(VT_files, read.csv)) %>% 
              mutate(day = as.Date(timestamp))


# Convert date to julian days
VT_comb_files$JulianDay <- format(VT_comb_files$day, "%j")

VT_Reflush <- VT_comb_files %>% filter(trait == "Reflush")

# extract unique values
VT_Reflush <- VT_Reflush[,c("plant_ID", "JulianDay","value")]
VT_Reflush <- unique(VT_Reflush)
VT_Reflush <- VT_Reflush[!VT_Reflush$value=="false",]

VT_Reflush <- VT_Reflush %>% pivot_wider(names_from = JulianDay, values_from = value)

# sort column order
VT_order <- sort(names(VT_Reflush))
length(VT_order)
VT_order <- VT_order[-length(VT_order)] # remove plant_ID
VT_order
VT_Reflush <- VT_Reflush[,c("plant_ID", "201", "202", "206", "212", "219", "225", "232", "241", "246", "253", "260")]

# change char to numeric
VT_Reflush[,c(2:length(VT_Reflush))] <- as.data.frame(sapply(VT_Reflush[,c(2:length(VT_Reflush))], as.numeric))

# convert to long format for modelling
names(VT_Reflush) # to check the days
VT_Reflush <- VT_Reflush %>% tidyr::pivot_longer(cols=c("201":"260"),
                                             names_to = "JDays",
                                             values_to = "reflush")
VT_Reflush$JDays <- as.numeric(VT_Reflush$JDays)
VT_Reflush$plant_ID <- as.factor(VT_Reflush$plant_ID)

VT_RF <- VT_Reflush[,c("plant_ID","reflush")]
VT_RF <- VT_RF[!is.na(VT_RF$reflush),]
VT_RF <- unique(VT_RF) # 160 unique reflush events
VT_RF <- as.data.frame(VT_RF)
# VT_RF is the final file for the reflush data

VT_RF$Garden <- "VT"
VT_RF$Family <- gsub("\\_VT.*", "", VT_RF$plant_ID)

VT_RF <- merge(x=VT_RF,
                 y=exome_meta[,c("Family","Region","Pop")],
                 by="Family")


```


## Maryland   
```{r}
## garden map
MD_gar <- read_csv("C:\\Dropbox\\Spruce_CommonGarden_Data\\MD_site\\MD_garden.csv")

## plant ID frame 
MD_frame <- MD_gar[,c("PlantOrder", "plant_ID")]


############## read in database files #########################################
MD_files <- list.files(path = "C:\\Dropbox\\Spruce_CommonGarden_Data\\MD_site\\MD_traitdataRAW\\budset_2020\\database", full.names = TRUE)

## Convert timestamp to date
MD_comb_files <- bind_rows(lapply(MD_files, fread)) %>% 
              mutate(day = as.Date(timestamp))

MD_comb_files <- MD_comb_files[,c("plant_ID", "Population","Family","Garden","Bed","trait","value","day")]

MD_Reflush <- MD_comb_files %>% filter(trait == "Reflush")

# extract unique values
MD_Reflush <- MD_Reflush[,c("plant_ID", "value")]
MD_Reflush <- unique(MD_Reflush)
MD_Reflush <- MD_Reflush[!MD_Reflush$value=="NA",]

MD_Reflush <- MD_Reflush %>% pivot_wider(names_from = value, values_from = value)

# sort column order
MD_order <- sort(names(MD_Reflush))
length(MD_order)
MD_order <- MD_order[-length(MD_order)] # remove plant_ID
MD_order

## Actual reflush data
MD_Reflush <- MD_Reflush[,c("plant_ID", "197", "199", "201", "202", "203", "204", "205", "206",
                            "208", "209", "210", "211", "213", "215", "216", "217", "218", "220",
                            "223", "224", "225", "231", "236", "237", "240")]

## reduced reflush data
### start from 204
# MD_Reflush <- MD_Reflush[,c("plant_ID", "204", "205", "206",
#                             "208", "209", "210", "211", "213", "215", "216", "217", "218", "220",
#                             "223", "224", "225", "231", "236", "237", "240")]

# change char to numeric
MD_Reflush[,c(2:length(MD_Reflush))] <- as.data.frame(sapply(MD_Reflush[,c(2:length(MD_Reflush))], as.numeric))

# convert to long format for modelling
names(MD_Reflush) # to check the days
MD_Reflush <- MD_Reflush %>% tidyr::pivot_longer(cols=c("197":"240"),
                                             names_to = "JDays",
                                             values_to = "reflush")
MD_Reflush$JDays <- as.numeric(MD_Reflush$JDays)
MD_Reflush$plant_ID <- as.factor(MD_Reflush$plant_ID)
MD_Reflush <- MD_Reflush[!is.na(MD_Reflush$reflush==T),]

MD_RF <- MD_Reflush[,c("plant_ID","reflush")]
MD_RF <- MD_RF[!is.na(MD_RF$reflush),]
MD_RF <- unique(MD_RF)

MD_RF$Garden <- "MD"
MD_RF$Family <- gsub("\\_MD.*", "", MD_RF$plant_ID)

MD_RF <- merge(x=MD_RF,
                 y=exome_meta[,c("Family","Region","Pop")],
                 by="Family")

```

## North Carolina  
```{r}
## garden map
NC_gar <- read_csv("C:\\Dropbox\\Spruce_CommonGarden_Data\\NC_site\\NC_garden.csv")

## plant ID frame 
NC_frame <- NC_gar[,c("PlantOrder", "plant_ID")]


############## read in database files #########################################
NC_files <- list.files(path = "C:\\Dropbox\\Spruce_CommonGarden_Data\\NC_site\\NC_traitdataRAW\\budset_2020", full.names = TRUE)

## Convert timestamp to date
NC_comb_files <- bind_rows(lapply(NC_files, fread)) %>% 
              mutate(day = as.Date(timestamp))

NC_comb_files <- NC_comb_files[,c("plant_ID", "Population","Family","Garden","Bed","trait","value","day")]

NC_Reflush <- NC_comb_files %>% filter(trait == "Reflush")
NC_Reflush <- NC_Reflush[!NC_Reflush$value == "true",]  
NC_Reflush <- NC_Reflush[!NC_Reflush$value == "false",]
NC_Reflush <- NC_Reflush[!NC_Reflush$value == "NA",]

# extract unique values
NC_Reflush <- NC_Reflush[,c("plant_ID", "value")] #skipped col: "JulianDay"
NC_Reflush <- unique(NC_Reflush)

NC_Reflush <- NC_Reflush %>% pivot_wider(names_from = value, values_from = value)

# sort column order
NC_order <- sort(names(NC_Reflush))
length(NC_order)
NC_order <- NC_order[-length(NC_order)] # remove plant_ID
NC_order
NC_Reflush <- NC_Reflush[,c("plant_ID", "197", "198", "202", "203", "209", "223", "231", "246", "248")]

# change char to numeric
NC_Reflush[,c(2:length(NC_Reflush))] <- as.data.frame(sapply(NC_Reflush[,c(2:length(NC_Reflush))], as.numeric))

# convert to long format for modelling
names(NC_Reflush) # to check the days
NC_Reflush <- NC_Reflush %>% tidyr::pivot_longer(cols=c("197":"248"),
                                             names_to = "JDays",
                                             values_to = "reflush")
NC_Reflush$JDays <- as.numeric(NC_Reflush$JDays)
NC_Reflush$plant_ID <- as.factor(NC_Reflush$plant_ID)

NC_RF <- NC_Reflush[,c("plant_ID","reflush")]
NC_RF <- NC_RF[!is.na(NC_RF$reflush),]
NC_RF <- unique(NC_RF)

NC_RF$Garden <- "NC"
NC_RF$Family <- gsub("\\_NC.*", "", NC_RF$plant_ID)

NC_RF <- merge(x=NC_RF,
                 y=exome_meta[,c("Family","Region","Pop")],
                 by="Family")
```

# Visualization  
```{r}
RF_dat <- rbind(VT_RF, MD_RF, NC_RF)
cols <- c("Family","Garden", "Region", "Pop")
RF_dat[,cols] <- lapply(RF_dat[,cols], as.factor)

# factor names and levels  
RF_dat$Garden <- revalue(RF_dat$Garden, c("VT"="Vermont", "MD"="Maryland", "NC"="North_Carolina")) 
RF_dat$Region <- revalue(RF_dat$Region, c("C"="Core", "M"="Margin", "E"="Edge")) 
RF_dat$Garden <- factor(RF_dat$Garden,levels = c("Vermont", "Maryland", "North_Carolina"))
RF_dat$Region <- factor(RF_dat$Region,levels = c("Core", "Margin", "Edge"))

RF_dat$Reflush <- NULL
RF_dat[RF_dat$reflush < 214,"Reflush"] <- "July"
RF_dat[RF_dat$reflush > 213 & RF_dat$reflush < 245,"Reflush"] <- "August"
RF_dat[RF_dat$reflush > 244 & RF_dat$reflush < 261,"Reflush"] <- "September"
RF_dat$reflush <- as.factor(RF_dat$reflush)
RF_dat$Reflush <- factor(RF_dat$Reflush, levels = c("July", "August", "September"))

RF_dt  <-  RF_dat %>% 
            group_by(Region, Garden, Reflush, Pop) %>% 
            dplyr::summarize(N = n())
RF_dt$Reflush <- factor(RF_dt$Reflush, levels = c("July", "August", "September"))

# three blocks
ggplot(data = RF_dt,
       aes(axis1 = Garden, axis2 = Region, axis3 = Reflush,
           y = N)) +
  scale_x_discrete(limits = c("Garden",  "Region", "Reflush"), expand = c(.1, .05)) +
  geom_alluvium(aes(fill = Region)) + 
  scale_color_viridis(option = "A", direction = -1)  +
  geom_stratum() + geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_bw() +
  # scale_fill_jama() +
  labs( y = "No. of individuals", title = "",
          subtitle = "", caption = "")
```


<!-- ```{echo=F} -->
<!-- # two blocks -->
<!-- ggplot(data = RF_dt, -->
<!--        aes(axis1 = Garden, axis3 = reflush, -->
<!--            y = N)) + -->
<!--   scale_x_discrete(limits = c("Garden", "reflush"), expand = c(.1, .05)) + -->
<!--   geom_alluvium(aes(fill = Region)) +  -->
<!--   scale_color_viridis(option = "A", direction = -1)  + -->
<!--   geom_stratum() + geom_text(stat = "stratum", aes(label = after_stat(stratum))) + -->
<!--   theme_minimal() + -->
<!--   # scale_fill_jama() + -->
<!--   labs( y = "No. of individuals", title = "", -->
<!--           subtitle = "", caption = "") -->
<!-- ``` -->




# Binomial model  
```{r}
# add bed 
RF_dat$plant_ID <- as.character(RF_dat$plant_ID)
RF_dat$mBed <- substring(RF_dat$plant_ID, nchar(RF_dat$plant_ID)-3)
RF_dat$plant_ID <- as.factor(RF_dat$plant_ID)

# prep the dataset
RF_bino <- left_join(RF_dat, exome_meta)
RF_bino <- RF_bino[,c("Family","plant_ID","Garden","Region","Pop","mBed","reflush","Reflush")]
colnames(RF_bino)[colnames(RF_bino) == "Pop"] <- "Population"
RF_bino$reflush_status <- 1

garden <- rbind(VT_gar, MD_gar, NC_gar)

# adding info for all the live plants at the end of the 2020 season
alive2020 <- read.csv("Z:\\Anoob\\MCMCglmm\\trait_data\\Growth_2020.csv", sep=",")
alive2020 <- alive2020[,c("Family","plant_ID","Garden","Region","Population", "mBed")]

RF_bino <- right_join(RF_bino, alive2020)
RF_bino <- RF_bino[,c("Family","plant_ID","Garden","Region","Population","mBed","reflush","Reflush","reflush_status")]
RF_bino[is.na(RF_bino$reflush_status),"reflush_status"] <- 0

# Model 
reflush_mod <- glmer(reflush_status ~ Garden * Region + (1|Family) + (1|Population) + (1|mBed),
                     data=RF_bino,
                     family=binomial(link="logit"))
summary(reflush_mod)

```

- Reflushing is significant at all three garden sites (p<0.0001).  
- Reflushing is significant for Edge (p=0.01) and Margin (p=0.05) at the Vermont garden.  
- Margin x North carolina interaction is also significant.   





