---
title: "Trait Plasticity based on climate transfer distance"
author: "Anoob Prakash"
date: "03/03/2021"
output: html_document
  rmarkdown::html_document:
    theme: cosmo  
    number_sections: false
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
# setwd("Z:/Anoob/MCMCglmm")

suppressPackageStartupMessages({
# packages
require(MCMCglmm)
require(lmerTest)
require(dplyr)
require(tidyr)
require(data.table)
require(ggplot2)
})

# data 
budset_2019 <- read.csv("./trait_data/BudSet_2019.csv")
budset_2020 <- read.csv("./trait_data/BudSet_2020.csv")
budbreak_2020 <- read.csv("./trait_data/BudBreak_2020_cGDD.csv")
heightGrowth_2019 <- read.csv("./trait_data/Growth_2019.csv")
heightGrowth_2020 <- read.csv("./trait_data/Growth_2020.csv")
Plasticity <- read.csv("./trait_data/Plasticity.csv")

```

## climate transfer distance  
 - CTD based on MAT  
 - Plasticity = (trait@home - trait@away ) / (trait@home)   
 
```{r}
Garden_MAT <- read.csv("./ClimateNA/envGarden_Year_2019Y.csv")
Garden_MAT

# MAT for 2020
# source: http://scacis.rcc-acis.org/  
VT_MAT <- round(((sum(26.1, 24.8, 37.3, 43.4, 57.9, 69.0, 76.8, 71.0, 62.1, 50.1, 43.3, 31.3)/12)-32)*(5/9),1)
MD_MAT <- round(((sum(31.7, 33.3, 43.3, 44.2, 54.4, 65.6, 73.5, 69.9, 60.5, 52.2, 45.4, 30.7)/12)-32)*(5/9),1)
NC_MAT <- round(((sum(40.2, 42.1, 51.6, 54.5, 60.7, 72.1, 79.3, 75.8, 66.0, 59.0, 51.7, 37.6)/12)-32)*(5/9),1)

Garden_MAT_2020 <- data.frame(Garden=c("VT_coords","MD_coords","NC_coords"),
                         MAT=c(VT_MAT,MD_MAT,NC_MAT))
Garden_MAT_2020
  
Provenance_MAT <- readxl::read_xlsx("./ClimateNA/spruce_envVar_PCA_210118.xlsx")
```

# Bud set 2019  
```{r}
# budset_2019$pMAT <- NA # provenance MAT
budset_2019$gMAT <- NA # garden MAT
budset_2019[budset_2019$Garden=="Vermont","gMAT"] <- Garden_MAT[Garden_MAT$ID1=="VT_coords","MAT"]
budset_2019[budset_2019$Garden=="Maryland","gMAT"] <- Garden_MAT[Garden_MAT$ID1=="MD_coords","MAT"]
budset_2019[budset_2019$Garden=="North_Carolina","gMAT"] <- Garden_MAT[Garden_MAT$ID1=="NC_coords","MAT"]

budset_2019 <- merge(x=budset_2019,
                     y=Provenance_MAT[,c("site","MAT")],
                     by.x="Population",
                     by.y="site")

colnames(budset_2019)[colnames(budset_2019)=="MAT"] <- "pMAT"
budset_2019$TD <- budset_2019$gMAT - budset_2019$pMAT
budset_2019$TD2 <- budset_2019$TD*budset_2019$TD # to check for the quadreatic relationship between transfer distance and response variable

# family_garden column
budset_2019 <- budset_2019 %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
# budset_2019 <- budset_2019 %>% unite(Pop_gardenID, Population, Garden, sep = "_", remove = FALSE)

# per site
budset_2019_VT <- budset_2019 %>% filter(Garden == "Vermont")
budset_2019_MD <- budset_2019 %>% filter(Garden == "Maryland")
budset_2019_NC <- budset_2019 %>% filter(Garden == "North_Carolina")

# Vemont
bs_2019_VT <- lmer(BudSet ~ 1 + (1|Bed) + (1|Family), budset_2019_VT)
bs_2019_VT <- coef(bs_2019_VT)
bs_2019_VT <- bs_2019_VT$Family
bs_2019_VT <- cbind(Family=rownames(bs_2019_VT),bs_2019_VT)
rownames(bs_2019_VT) <- NULL

# Maryland
bs_2019_MD <- lmer(BudSet ~ 1 + (1|Bed) + (1|Family), budset_2019_MD)
bs_2019_MD <- coef(bs_2019_MD)
bs_2019_MD <- bs_2019_MD$Family
bs_2019_MD <- cbind(Family=rownames(bs_2019_MD),bs_2019_MD)
rownames(bs_2019_MD) <- NULL

# North Carolina
bs_2019_NC <- lmer(BudSet ~ 1 + (1|Bed) + (1|Family), budset_2019_NC)
bs_2019_NC <- coef(bs_2019_NC)
bs_2019_NC <- bs_2019_NC$Family
bs_2019_NC <- cbind(Family=rownames(bs_2019_NC),bs_2019_NC)
rownames(bs_2019_NC) <- NULL

# large no .of families missing at the NC site, remove the excess families from other sites
bs_2019_VT <- bs_2019_VT[(bs_2019_VT$Family %in% bs_2019_NC$Family),]; nrow(bs_2019_VT[(bs_2019_VT$Family %in% bs_2019_MD$Family),])
bs_2019_MD <- bs_2019_MD[(bs_2019_MD$Family %in% bs_2019_NC$Family),]

# add garden column
bs_2019_VT$Garden <- "Vermont"
bs_2019_MD$Garden <- "Maryland"
bs_2019_NC$Garden <- "North_Carolina"

bs_2019_VT <- bs_2019_VT %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
bs_2019_MD <- bs_2019_MD %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
bs_2019_NC <- bs_2019_NC %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)

# combine family level data
budsetPlasticity_2019 <- rbind(bs_2019_VT,bs_2019_MD,bs_2019_NC)
colnames(budsetPlasticity_2019)[colnames(budsetPlasticity_2019)=="(Intercept)"] <- "BudSet_2019"

# add transfer distance
budsetPlasticity_2019 <- merge(x=budsetPlasticity_2019,
                                y=budset_2019[,c("Family_gardenID","TD","TD2")],
                               by="Family_gardenID")
```

**Budset 2019 v CTD**  
```{r}

budset_2019$Region <- factor(budset_2019$Region,levels = c("Core", "Margin", "Edge")) 

budset_2019_modTD <- lmer(BudSet ~ Garden * Region + TD + (1|Family) + (1|Population), data=budset_2019)
summary(budset_2019_modTD)

# trait vs TD
ggplot(data=budset_2019,
         aes(x= TD,y=BudSet, color=Region)) + 
          geom_point(aes(shape = Region), size=2, alpha = 0.2) + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2)) +
              scale_color_manual(values = c("Core" = "goldenrod2","Edge"="steelblue","Margin"="green2")) +
                labs(x = "Climate Transfer Distance", 
                     y = "Bud set in 2019 (DOY)") + 
                  theme_bw() + theme(axis.text=element_text(size=14), 
                       axis.title=element_text(size=14,face="bold"),
                       legend.title = element_text(color = "black", size = 14),
                       legend.text = element_text(color = "black", size = 13))
```


```{r}
budsetPlasticity_2019 <- as.data.table(budsetPlasticity_2019)
budset_2019_home <- setDT(budsetPlasticity_2019)[, .SD[which.min(abs(TD))], by=Family]
budset_2019_away <- setDT(budsetPlasticity_2019)[, .SD[which.max(abs(TD))], by=Family]

colnames(budset_2019_home)[colnames(budset_2019_home)=="BudSet_2019"] <- "home"
colnames(budset_2019_away)[colnames(budset_2019_away)=="BudSet_2019"] <- "away"
budsetPlasticity_2019 <- merge(x=budset_2019_home[,-c("TD","TD2")],
                               y=budset_2019_away[,c("Family","away")],
                               by="Family")
budsetPlasticity_2019$BudSet2019_Plasticity <- (budsetPlasticity_2019$home - budsetPlasticity_2019$away)/budsetPlasticity_2019$home

```
 
# Bud set 2020  
```{r}
# budset_2020$pMAT <- NA # provenance MAT
budset_2020$gMAT <- NA # garden MAT
budset_2020[budset_2020$Garden=="Vermont","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="VT_coords","MAT"]
budset_2020[budset_2020$Garden=="Maryland","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="MD_coords","MAT"]
budset_2020[budset_2020$Garden=="North_Carolina","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="NC_coords","MAT"]

budset_2020 <- merge(x=budset_2020,
                     y=Provenance_MAT[,c("site","MAT")],
                     by.x="Population",
                     by.y="site")

colnames(budset_2020)[colnames(budset_2020)=="MAT"] <- "pMAT"
budset_2020$TD <- budset_2020$gMAT - budset_2020$pMAT
budset_2020$TD2 <- budset_2020$TD*budset_2020$TD # to check for the quadreatic relationship between transfer distance and response variable

# family_garden column
budset_2020 <- budset_2020 %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
# budset_2020 <- budset_2020 %>% unite(Pop_gardenID, Population, Garden, sep = "_", remove = FALSE)

# per site
budset_2020_VT <- budset_2020 %>% filter(Garden == "Vermont")
budset_2020_MD <- budset_2020 %>% filter(Garden == "Maryland")
budset_2020_NC <- budset_2020 %>% filter(Garden == "North_Carolina")

# Vemont
bs_2020_VT <- lmer(BudSet ~ 1 + (1|Bed) + (1|Family), budset_2020_VT)
bs_2020_VT <- coef(bs_2020_VT)
bs_2020_VT <- bs_2020_VT$Family
bs_2020_VT <- cbind(Family=rownames(bs_2020_VT),bs_2020_VT)
rownames(bs_2020_VT) <- NULL

# Maryland
bs_2020_MD <- lmer(BudSet ~ 1 + (1|Bed) + (1|Family), budset_2020_MD)
bs_2020_MD <- coef(bs_2020_MD)
bs_2020_MD <- bs_2020_MD$Family
bs_2020_MD <- cbind(Family=rownames(bs_2020_MD),bs_2020_MD)
rownames(bs_2020_MD) <- NULL

# North Carolina
bs_2020_NC <- lmer(BudSet ~ 1 + (1|Bed) + (1|Family), budset_2020_NC)
bs_2020_NC <- coef(bs_2020_NC)
bs_2020_NC <- bs_2020_NC$Family
bs_2020_NC <- cbind(Family=rownames(bs_2020_NC),bs_2020_NC)
rownames(bs_2020_NC) <- NULL

# large no .of families missing at the NC site, remove the excess families from other sites
bs_2020_VT <- bs_2020_VT[(bs_2020_VT$Family %in% bs_2020_NC$Family),]; nrow(bs_2020_VT[(bs_2020_VT$Family %in% bs_2020_MD$Family),])
bs_2020_MD <- bs_2020_MD[(bs_2020_MD$Family %in% bs_2020_NC$Family),]

# add garden column
bs_2020_VT$Garden <- "Vermont"
bs_2020_MD$Garden <- "Maryland"
bs_2020_NC$Garden <- "North_Carolina"

bs_2020_VT <- bs_2020_VT %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
bs_2020_MD <- bs_2020_MD %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
bs_2020_NC <- bs_2020_NC %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)

# combine family level data
budsetPlasticity_2020 <- rbind(bs_2020_VT,bs_2020_MD,bs_2020_NC)
colnames(budsetPlasticity_2020)[colnames(budsetPlasticity_2020)=="(Intercept)"] <- "BudSet_2020"

# add transfer distance
budsetPlasticity_2020 <- merge(x=budsetPlasticity_2020,
                                y=budset_2020[,c("Family_gardenID","TD","TD2")],
                                by="Family_gardenID")
# trait vs TD
ggplot(data=budset_2020,
         aes(x= TD,y=BudSet)) + 
          geom_point() + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2))  


budsetPlasticity_2020 <- as.data.table(budsetPlasticity_2020)
budset_2020_home <- setDT(budsetPlasticity_2020)[, .SD[which.min(abs(TD))], by=Family]
budset_2020_away <- setDT(budsetPlasticity_2020)[, .SD[which.max(abs(TD))], by=Family]

colnames(budset_2020_home)[colnames(budset_2020_home)=="BudSet_2020"] <- "home"
colnames(budset_2020_away)[colnames(budset_2020_away)=="BudSet_2020"] <- "away"
budsetPlasticity_2020 <- merge(x=budset_2020_home[,-c("TD","TD2")],
                               y=budset_2020_away[,c("Family","away")],
                               by="Family")
budsetPlasticity_2020$BudSet2020_Plasticity <- (budsetPlasticity_2020$home - budsetPlasticity_2020$away)/budsetPlasticity_2020$home
```

**Budset 2020 v CTD**  
```{r}

budset_2020$Region <- factor(budset_2020$Region,levels = c("Core", "Margin", "Edge")) 

budset_2020_modTD <- lmer(BudSet ~ Garden * Region + TD + (1|Family) + (1|Population), data=budset_2020)
summary(budset_2020_modTD)

# trait vs TD
ggplot(data=budset_2020,
         aes(x= TD,y=BudSet, color=Region)) + 
          geom_point(aes(shape = Region), size=2, alpha = 0.2) + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2)) +
              scale_color_manual(values = c("Core" = "goldenrod2","Margin"="green2", "Edge"="steelblue")) +
                labs(x = "Climate Transfer Distance", 
                     y = "Bud set in 2020 (DOY)") + 
                  theme_bw() + theme(axis.text=element_text(size=14), 
                       axis.title=element_text(size=14,face="bold"),
                       legend.title = element_text(color = "black", size = 14),
                       legend.text = element_text(color = "black", size = 13))
```




# Bud break 2020  
```{r}
budbreak_2020$gMAT <- NA # garden MAT
budbreak_2020[budbreak_2020$Garden=="Vermont","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="VT_coords","MAT"]
budbreak_2020[budbreak_2020$Garden=="Maryland","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="MD_coords","MAT"]
budbreak_2020[budbreak_2020$Garden=="North_Carolina","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="NC_coords","MAT"]

budbreak_2020 <- merge(x=budbreak_2020,
                     y=Provenance_MAT[,c("site","MAT")],
                     by.x="Population",
                     by.y="site")

colnames(budbreak_2020)[colnames(budbreak_2020)=="MAT"] <- "pMAT"
budbreak_2020$TD <- budbreak_2020$gMAT - budbreak_2020$pMAT
budbreak_2020$TD2 <- budbreak_2020$TD*budbreak_2020$TD # to check for the quadreatic relationship between transfer distance and response variable

# family_garden column
budbreak_2020 <- budbreak_2020 %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
# budbreak_2020 <- budbreak_2020 %>% unite(Pop_gardenID, Population, Garden, sep = "_", remove = FALSE)

# per site
budbreak_2020_VT <- budbreak_2020 %>% filter(Garden == "Vermont")
budbreak_2020_MD <- budbreak_2020 %>% filter(Garden == "Maryland")
budbreak_2020_NC <- budbreak_2020 %>% filter(Garden == "North_Carolina")

# Vemont
bb_2020_VT <- lmer(cGDD ~ 1 + (1|Bed) + (1|Family), budbreak_2020_VT,na.action=na.omit)
bb_2020_VT <- coef(bb_2020_VT)
bb_2020_VT <- bb_2020_VT$Family
bb_2020_VT <- cbind(Family=rownames(bb_2020_VT),bb_2020_VT)
rownames(bb_2020_VT) <- NULL

# Maryland
bb_2020_MD <- lmer(cGDD ~ 1 + (1|Bed) + (1|Family), budbreak_2020_MD,na.action=na.omit)
bb_2020_MD <- coef(bb_2020_MD)
bb_2020_MD <- bb_2020_MD$Family
bb_2020_MD <- cbind(Family=rownames(bb_2020_MD),bb_2020_MD)
rownames(bb_2020_MD) <- NULL

# North Carolina
bb_2020_NC <- lmer(cGDD ~ 1 + (1|Bed) + (1|Family), budbreak_2020_NC,na.action=na.omit)
bb_2020_NC <- coef(bb_2020_NC)
bb_2020_NC <- bb_2020_NC$Family
bb_2020_NC <- cbind(Family=rownames(bb_2020_NC),bb_2020_NC)
rownames(bb_2020_NC) <- NULL

# large no .of families missing at the NC site, remove the excess families from other sites
bb_2020_VT <- bb_2020_VT[(bb_2020_VT$Family %in% bb_2020_NC$Family),]; nrow(bb_2020_VT[(bb_2020_VT$Family %in% bb_2020_MD$Family),])
bb_2020_MD <- bb_2020_MD[(bb_2020_MD$Family %in% bb_2020_NC$Family),]

# add garden column
bb_2020_VT$Garden <- "Vermont"
bb_2020_MD$Garden <- "Maryland"
bb_2020_NC$Garden <- "North_Carolina"

bb_2020_VT <- bb_2020_VT %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
bb_2020_MD <- bb_2020_MD %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
bb_2020_NC <- bb_2020_NC %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)

# combine family level data
budbreakPlasticity_2020 <- rbind(bb_2020_VT,bb_2020_MD,bb_2020_NC)
colnames(budbreakPlasticity_2020)[colnames(budbreakPlasticity_2020)=="(Intercept)"] <- "BudBreak_2020"

# add transfer distance
budbreakPlasticity_2020 <- merge(x=budbreakPlasticity_2020,
                                y=budbreak_2020[,c("Family_gardenID","TD","TD2")],
                                by="Family_gardenID")
```


```{r}
# trait vs TD
ggplot(data=budbreak_2020,
         aes(x= TD,y=cGDD)) + 
          geom_point() + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2))
```

**Budbreak 2020 v CTD**  
```{r}

budbreak_2020$Region <- factor(budbreak_2020$Region,levels = c("Core", "Margin", "Edge")) 
budbreak_2020 <- budbreak_2020 %>% unite(mBed, Garden, Bed, sep = "_", remove = FALSE)
  
budbreak_2020_modTD <- lmer(cGDD ~ Garden * Region + TD + (1|Family) + (1|Population) + (1|mBed),
                            data=budbreak_2020, na.action = na.exclude)
summary(budbreak_2020_modTD)

# trait vs TD
ggplot(data=budbreak_2020,
         aes(x= TD,y=cGDD, color=Region)) + 
          geom_point(aes(shape = Region), size=2, alpha = 0.1) + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2)) +
              scale_color_manual(values = c("Core" = "goldenrod2","Edge"="steelblue","Margin"="green2")) +
                labs(x = "Climate Transfer Distance", 
                     y = "Bud break in 2020 (cGDD)") + 
                  theme_bw() + theme(axis.text=element_text(size=14), 
                       axis.title=element_text(size=14,face="bold"),
                       legend.title = element_text(color = "black", size = 14),
                       legend.text = element_text(color = "black", size = 13))
```

```{r}
budbreakPlasticity_2020 <- as.data.table(budbreakPlasticity_2020)
budbreak_2020_home <- setDT(budbreakPlasticity_2020)[, .SD[which.min(abs(TD))], by=Family]
budbreak_2020_away <- setDT(budbreakPlasticity_2020)[, .SD[which.max(abs(TD))], by=Family]

colnames(budbreak_2020_home)[colnames(budbreak_2020_home)=="BudBreak_2020"] <- "home"
colnames(budbreak_2020_away)[colnames(budbreak_2020_away)=="BudBreak_2020"] <- "away"
budbreakPlasticity_2020 <- merge(x=budbreak_2020_home[,-c("TD","TD2")],
                               y=budbreak_2020_away[,c("Family","away")],
                               by="Family")
budbreakPlasticity_2020$BudBreak2020_Plasticity <- (budbreakPlasticity_2020$home - budbreakPlasticity_2020$away)/budbreakPlasticity_2020$home
```

# Growth 2019  
```{r}
# heightGrowth_2019$pMAT <- NA # provenance MAT
heightGrowth_2019$gMAT <- NA # garden MAT
heightGrowth_2019[heightGrowth_2019$Garden=="Vermont","gMAT"] <- Garden_MAT[Garden_MAT$ID1=="VT_coords","MAT"]
heightGrowth_2019[heightGrowth_2019$Garden=="Maryland","gMAT"] <- Garden_MAT[Garden_MAT$ID1=="MD_coords","MAT"]
heightGrowth_2019[heightGrowth_2019$Garden=="North_Carolina","gMAT"] <- Garden_MAT[Garden_MAT$ID1=="NC_coords","MAT"]

heightGrowth_2019 <- merge(x=heightGrowth_2019,
                     y=Provenance_MAT[,c("site","MAT")],
                     by.x="Population",
                     by.y="site")

colnames(heightGrowth_2019)[colnames(heightGrowth_2019)=="MAT"] <- "pMAT"
heightGrowth_2019$TD <- heightGrowth_2019$gMAT - heightGrowth_2019$pMAT
heightGrowth_2019$TD2 <- heightGrowth_2019$TD*heightGrowth_2019$TD # to check for the quadreatic relationship between transfer distance and response variable

# family_garden column
heightGrowth_2019 <- heightGrowth_2019 %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
# heightGrowth_2019 <- heightGrowth_2019 %>% unite(Pop_gardenID, Population, Garden, sep = "_", remove = FALSE)

# per site
heightGrowth_2019_VT <- heightGrowth_2019 %>% filter(Garden == "Vermont")
heightGrowth_2019_MD <- heightGrowth_2019 %>% filter(Garden == "Maryland")
heightGrowth_2019_NC <- heightGrowth_2019 %>% filter(Garden == "North_Carolina")

# Vemont
gw_2019_VT <- lmer(Growth ~ 1 + (1|Bed) + (1|Family), heightGrowth_2019_VT,na.action=na.omit)
gw_2019_VT <- coef(gw_2019_VT)
gw_2019_VT <- gw_2019_VT$Family
gw_2019_VT <- cbind(Family=rownames(gw_2019_VT),gw_2019_VT)
rownames(gw_2019_VT) <- NULL

# Maryland
gw_2019_MD <- lmer(Growth ~ 1 + (1|Bed) + (1|Family), heightGrowth_2019_MD,na.action=na.omit)
gw_2019_MD <- coef(gw_2019_MD)
gw_2019_MD <- gw_2019_MD$Family
gw_2019_MD <- cbind(Family=rownames(gw_2019_MD),gw_2019_MD)
rownames(gw_2019_MD) <- NULL

# North Carolina
gw_2019_NC <- lmer(Growth ~ 1 + (1|Bed) + (1|Family), heightGrowth_2019_NC,na.action=na.omit)
gw_2019_NC <- coef(gw_2019_NC)
gw_2019_NC <- gw_2019_NC$Family
gw_2019_NC <- cbind(Family=rownames(gw_2019_NC),gw_2019_NC)
rownames(gw_2019_NC) <- NULL

# large no .of families missing at the NC site, remove the excess families from other sites
gw_2019_VT <- gw_2019_VT[(gw_2019_VT$Family %in% gw_2019_NC$Family),]; nrow(gw_2019_VT[(gw_2019_VT$Family %in% gw_2019_MD$Family),])
gw_2019_MD <- gw_2019_MD[(gw_2019_MD$Family %in% gw_2019_NC$Family),]

# add garden column
gw_2019_VT$Garden <- "Vermont"
gw_2019_MD$Garden <- "Maryland"
gw_2019_NC$Garden <- "North_Carolina"

gw_2019_VT <- gw_2019_VT %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
gw_2019_MD <- gw_2019_MD %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
gw_2019_NC <- gw_2019_NC %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)

# combine family level data
growthPlasticity_2019 <- rbind(gw_2019_VT,gw_2019_MD,gw_2019_NC)
colnames(growthPlasticity_2019)[colnames(growthPlasticity_2019)=="(Intercept)"] <- "Growth_2019"

# add transfer distance
growthPlasticity_2019 <- merge(x=growthPlasticity_2019,
                                y=heightGrowth_2019[,c("Family_gardenID","TD","TD2")],
                                by="Family_gardenID")
# trait vs TD
ggplot(data=heightGrowth_2019,
         aes(x= TD,y=Growth)) + 
          geom_point() + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2))  


growthPlasticity_2019 <- as.data.table(growthPlasticity_2019)
heightGrowth_2019_home <- setDT(growthPlasticity_2019)[, .SD[which.min(abs(TD))], by=Family]
heightGrowth_2019_away <- setDT(growthPlasticity_2019)[, .SD[which.max(abs(TD))], by=Family]

colnames(heightGrowth_2019_home)[colnames(heightGrowth_2019_home)=="Growth_2019"] <- "home"
colnames(heightGrowth_2019_away)[colnames(heightGrowth_2019_away)=="Growth_2019"] <- "away"
growthPlasticity_2019 <- merge(x=heightGrowth_2019_home[,-c("TD","TD2")],
                               y=heightGrowth_2019_away[,c("Family","away")],
                               by="Family")
growthPlasticity_2019$growth2019_Plasticity <- (growthPlasticity_2019$home - growthPlasticity_2019$away)/growthPlasticity_2019$home
```

**Growth 2019 v CTD**  
```{r}

heightGrowth_2019$Region <- factor(heightGrowth_2019$Region,levels = c("Core", "Margin", "Edge")) 
heightGrowth_2019 <- heightGrowth_2019 %>% unite(mBed, Garden, Bed, sep = "_", remove = FALSE)
  
heightGrowth_2019_modTD <- lmer(Growth ~ Garden * Region + TD + (1|Family) + (1|Population) + (1|mBed),
                            data=heightGrowth_2019, na.action = na.exclude)
summary(heightGrowth_2019_modTD)

# trait vs TD
ggplot(data=heightGrowth_2019,
         aes(x= TD,y=Growth, color=Region)) + 
          geom_point(aes(shape = Region), size=2, alpha = 0.1) + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2)) +
              scale_color_manual(values = c("Core" = "goldenrod2","Edge"="steelblue","Margin"="green2")) +
                labs(x = "Climate Transfer Distance", 
                     y = "Growth in 2019") + 
                  theme_bw() + theme(axis.text=element_text(size=14), 
                       axis.title=element_text(size=14,face="bold"),
                       legend.title = element_text(color = "black", size = 14),
                       legend.text = element_text(color = "black", size = 13))
```

# Growth 2020  
```{r}
# heightGrowth_2020$pMAT <- NA # provenance MAT
heightGrowth_2020$gMAT <- NA # garden MAT
heightGrowth_2020[heightGrowth_2020$Garden=="Vermont","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="VT_coords","MAT"]
heightGrowth_2020[heightGrowth_2020$Garden=="Maryland","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="MD_coords","MAT"]
heightGrowth_2020[heightGrowth_2020$Garden=="North_Carolina","gMAT"] <- Garden_MAT_2020[Garden_MAT_2020$Garden=="NC_coords","MAT"]

heightGrowth_2020 <- merge(x=heightGrowth_2020,
                     y=Provenance_MAT[,c("site","MAT")],
                     by.x="Population",
                     by.y="site")

colnames(heightGrowth_2020)[colnames(heightGrowth_2020)=="MAT"] <- "pMAT"
heightGrowth_2020$TD <- heightGrowth_2020$gMAT - heightGrowth_2020$pMAT
heightGrowth_2020$TD2 <- heightGrowth_2020$TD*heightGrowth_2020$TD # to check for the quadratic relationship between transfer distance and response variable

# family_garden column
heightGrowth_2020 <- heightGrowth_2020 %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
# heightGrowth_2020 <- heightGrowth_2020 %>% unite(Pop_gardenID, Population, Garden, sep = "_", remove = FALSE)

# per site
heightGrowth_2020_VT <- heightGrowth_2020 %>% filter(Garden == "Vermont")
heightGrowth_2020_MD <- heightGrowth_2020 %>% filter(Garden == "Maryland")
heightGrowth_2020_NC <- heightGrowth_2020 %>% filter(Garden == "North_Carolina")

# Vemont
gw_2020_VT <- lmer(Growth ~ 1 + (1|Bed) + (1|Family), heightGrowth_2020_VT,na.action=na.omit)
gw_2020_VT <- coef(gw_2020_VT)
gw_2020_VT <- gw_2020_VT$Family
gw_2020_VT <- cbind(Family=rownames(gw_2020_VT),gw_2020_VT)
rownames(gw_2020_VT) <- NULL

# Maryland
gw_2020_MD <- lmer(Growth ~ 1 + (1|Bed) + (1|Family), heightGrowth_2020_MD,na.action=na.omit)
gw_2020_MD <- coef(gw_2020_MD)
gw_2020_MD <- gw_2020_MD$Family
gw_2020_MD <- cbind(Family=rownames(gw_2020_MD),gw_2020_MD)
rownames(gw_2020_MD) <- NULL

# North Carolina
gw_2020_NC <- lmer(Growth ~ 1 + (1|Bed) + (1|Family), heightGrowth_2020_NC,na.action=na.omit)
gw_2020_NC <- coef(gw_2020_NC)
gw_2020_NC <- gw_2020_NC$Family
gw_2020_NC <- cbind(Family=rownames(gw_2020_NC),gw_2020_NC)
rownames(gw_2020_NC) <- NULL

# large no .of families missing at the NC site, remove the excess families from other sites
gw_2020_VT <- gw_2020_VT[(gw_2020_VT$Family %in% gw_2020_NC$Family),]; nrow(gw_2020_VT[(gw_2020_VT$Family %in% gw_2020_MD$Family),])
gw_2020_MD <- gw_2020_MD[(gw_2020_MD$Family %in% gw_2020_NC$Family),]

# add garden column
gw_2020_VT$Garden <- "Vermont"
gw_2020_MD$Garden <- "Maryland"
gw_2020_NC$Garden <- "North_Carolina"

gw_2020_VT <- gw_2020_VT %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
gw_2020_MD <- gw_2020_MD %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)
gw_2020_NC <- gw_2020_NC %>% unite(Family_gardenID, Family, Garden, sep = "_", remove = FALSE)

# combine family level data
growthPlasticity_2020 <- rbind(gw_2020_VT,gw_2020_MD,gw_2020_NC)
colnames(growthPlasticity_2020)[colnames(growthPlasticity_2020)=="(Intercept)"] <- "Growth_2020"

# add transfer distance
growthPlasticity_2020 <- merge(x=growthPlasticity_2020,
                                y=heightGrowth_2020[,c("Family_gardenID","TD","TD2")],
                                by="Family_gardenID")
```


```{r}
# trait vs TD
ggplot(data=heightGrowth_2020,
         aes(x= TD,y=Growth)) + 
          geom_point() + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2))
```

**Growth 2020 v CTD**  
```{r}

heightGrowth_2020$Region <- factor(heightGrowth_2020$Region,levels = c("Core", "Margin", "Edge")) 
heightGrowth_2020 <- heightGrowth_2020 %>% unite(mBed, Garden, Bed, sep = "_", remove = FALSE)
  
heightGrowth_2020_modTD <- lmer(Growth ~ Garden * Region + TD + (1|Family) + (1|Population) + (1|mBed),
                            data=heightGrowth_2020, na.action = na.exclude)
summary(heightGrowth_2020_modTD)

# trait vs TD
ggplot(data=heightGrowth_2020,
         aes(x= TD,y=Growth, color=Region)) + 
          geom_point(aes(shape = Region), size=2, alpha = 0.1) + 
            geom_smooth(method='lm', se=F, formula=y~poly(x,2)) +
              scale_color_manual(values = c("Core" = "goldenrod2","Edge"="steelblue","Margin"="green2")) +
                labs(x = "Climate Transfer Distance", 
                     y = "Growth in 2020") + 
                  theme_bw() + theme(axis.text=element_text(size=14), 
                       axis.title=element_text(size=14,face="bold"),
                       legend.title = element_text(color = "black", size = 14),
                       legend.text = element_text(color = "black", size = 13))
```

```{r}
growthPlasticity_2020 <- as.data.table(growthPlasticity_2020)
heightGrowth_2020_home <- setDT(growthPlasticity_2020)[, .SD[which.min(abs(TD))], by=Family] #.SD stands for subset of data table
heightGrowth_2020_away <- setDT(growthPlasticity_2020)[, .SD[which.max(abs(TD))], by=Family]

colnames(heightGrowth_2020_home)[colnames(heightGrowth_2020_home)=="Growth_2020"] <- "home"
colnames(heightGrowth_2020_away)[colnames(heightGrowth_2020_away)=="Growth_2020"] <- "away"
growthPlasticity_2020 <- merge(x=heightGrowth_2020_home[,-c("TD","TD2")],
                               y=heightGrowth_2020_away[,c("Family","away")],
                               by="Family")
growthPlasticity_2020$growth2020_Plasticity <- (growthPlasticity_2020$home - growthPlasticity_2020$away)/growthPlasticity_2020$home
```

# Plasticity_TD  
```{r}
Plasticity_TD <- merge(x=Plasticity[,c(2:10)],y=budsetPlasticity_2019[,c("Family","BudSet2019_Plasticity")],by="Family",all.x=T)
Plasticity_TD <- merge(x=Plasticity_TD,y=budsetPlasticity_2020[,c("Family","BudSet2020_Plasticity")],by="Family",all.x=T)
Plasticity_TD <- merge(x=Plasticity_TD,y=budbreakPlasticity_2020[,c("Family","BudBreak2020_Plasticity")],by="Family",all.x=T)
Plasticity_TD <- merge(x=Plasticity_TD,y=growthPlasticity_2019[,c("Family","growth2019_Plasticity")],by="Family",all.x=T)
Plasticity_TD <- merge(x=Plasticity_TD,y=growthPlasticity_2020[,c("Family","growth2020_Plasticity")],by="Family",all.x=T)

# write.csv(Plasticity_TD, "./trait_data/Plasticity_TD.csv")
```

# Away vs Home gardens  
```{r}
table(heightGrowth_2020_home$Garden)

table(heightGrowth_2020_away$Garden)
```

