---
title: "Genotypic variation and plasticity in climate-adaptive traits after range expansion and fragmentation of red spruce (*Picea rubens* Sarg.)"
author: "Anoob Prakash"
output:
  rmarkdown::html_document:
    theme: cosmo  
    number_sections: false
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Contact

------------------------------------------------------------------------

**Affiliation** : Keller Lab; Department of Plant Biology, University of Vermont\
**E-mail contact**: [anoob.prakash\@uvm.edu](mailto:anoob.prakash@uvm.edu){.email} , [anoobvinu\@gmail.com](mailto:anoob.vinu@gmail.com){.email}\
**GitHub repository** : [anoobvinu07](https://github.com/anoobvinu07/NSF_RedSpruce_CG){.uri}\
**License** : [CC0-1.0](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/main/LICENSE)

------------------------------------------------------------------------

# Materials and Methods {.tabset .tabset-fade .tabset-pills}

This page provides information on the study conducted on red spruce across its range in order to understand the genetic variation and plasticity present in the species that might facilitate its adaptation to climate change.

## Map

![Map of the geographic locations of 65 Picea rubens populations (circles) sampled for this study. Colors indicate the assignment to geo-genetic regions based on genomic analyses. The three common garden sites at Vermont, Maryland and North Carolina are indicated as grey squares along with the elevation (m.a.s.l.) at which they are located. The orange-red shaded area on the map indicates the known range extent of red spruce](./Figure1_Map2.png)

## Data

The data used for this study are provided here. The meta data for the whole study system is at 1. The curated data for the trait for bud set, bud break and height growth for each season (2019 and 2020) are provided in the table at 2. The plasticity for all the traits are given as complete data at 3, along with bud break in day of year (DOY) provided in the supplementary. Finally, the PCA scores and PCA loading for defining the climate space and the PCA plot are at 4.

+--------+:---------------:+:---------------------------------------------------------:+:-----------------------------------------------------------------:+
| Sl No. |                 | Main Text                                                 | Supplementary                                                     |
+--------+-----------------+-----------------------------------------------------------+-------------------------------------------------------------------+
| 1      | Meta            | [Meta data](./data/meta/RS_Exome_metadata.txt)            |                                                                   |
+--------+-----------------+-----------------------------------------------------------+-------------------------------------------------------------------+
| 2      | Trait Data      | [Bud Break (2020)](./data/trait_data/BudBreak_2020.csv)   |                                                                   |
|        |                 |                                                           |                                                                   |
|        |                 | [Bud Set (2019)](./data/trait_data/BudSet_2019.csv)       |                                                                   |
|        |                 |                                                           |                                                                   |
|        |                 | [Bud Set (2020)](./data/trait_data/BudSet_2020.csv)       |                                                                   |
|        |                 |                                                           |                                                                   |
|        |                 | [Growth (2019)](./data/trait_data/Growth_2019.csv)        |                                                                   |
|        |                 |                                                           |                                                                   |
|        |                 | [Growth (2020)](./data/trait_data/Growth_2020.csv)        |                                                                   |
+--------+-----------------+-----------------------------------------------------------+-------------------------------------------------------------------+
| 3      | Plasticity Data | [Complete data](./data/plasticity_data/Plasticity_TD.csv) | [Bud break (DOY)](./data/plasticity_data/Plasticity_TD_bbDOY.csv) |
+--------+-----------------+-----------------------------------------------------------+-------------------------------------------------------------------+
| 4      | PC scores       | [PCA scores](./data/PCA/PCA_score.csv)                    |                                                                   |
|        |                 |                                                           |                                                                   |
|        |                 | [PCA loadings](./data/PCA/PCA_loadings.csv)               |                                                                   |
+--------+-----------------+-----------------------------------------------------------+-------------------------------------------------------------------+

: Data used for statistical analysis

## Methods

Statistical methods used to answer research question 1 are in climate transfer distance (1), climate data and the PCA (first half of PCA and Plasticity (6)), genetic variation and GxE (2) and broad sense heritability (3).

The second research questions looks into the genetic correlation that may be present between the traits (4). Genetic correlation and broad sense heritability was estimated using Bayesian appraoches (MCMCglmm models).

Finally, the third research question dwelled into the plasticity present in the traits (5) and whether these plasticities were adaptive or mal-adaptive in nature (second half of PCA and Plasticity (6)).

+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| Sl No. | Scripts                                                                                                                                                                                                                         | html                                                                  |
+:======:+:===============================================================================================================================================================================================================================:+:=====================================================================:+
| 1      | [Climate transfer distance](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/main/5_traitPlasticity_TD.Rmd)                                                                                                                 | [Climate transfer distance](./5_traitPlasticity_TD.html)              |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 2      | [Genetic variation and GxE](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/main/0_reaction_norms.Rmd)                                                                                                                     | [Genetic variation and GxE](./0_reaction_norms.html)                  |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 3      | [MCMCglmm model](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/main/1_heritability.R) ; [Heritability Estimate per garden](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/main/2_heritability_values_per_garden.R) | NA                                                                    |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 4      | [MCMCglmm model](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/main/3_genetic_correlation_MCMCmodel_final.R)                                                                                                             | [Genetic Correlation](./4_genetic_correlation_plots.html)             |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 5      | [Trait Platicity](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/43568608406da6a6abf7ee74a50b7509ea2bacc2/7_traitPlasticity_family_and_pop_blup_plots.Rmd)                                                                | [Trait Platicity](./7_traitPlasticity_family_and_pop_blup_plots.html) |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| 6      | [PCA and Plasticity](https://github.com/anoobvinu07/NSF_RedSpruce_CG/blob/main/10_PCA_and_Plasticity.Rmd)                                                                                                                       | [PCA and Plasticity](./10_PCA_and_Plasticity.html)                    |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+

: Statistical analysis and major findings of the study
